### ISSUE TITLE
Updates required to parse new MAME XML structure

### ISSUE THREAD

**Issue by nullpainter** [mika76/mamesaver#3]
The MAME XML structure has changed very subtly since this project was created. All that is required to get it to work with new versions of MAME is to change the following line in `Mamesaver.cs` from:

```c#
XmlNode xmlGame = doc.SelectSingleNode(string.Format("mame/game[@name='{0}']", key));
```

to:

```c#
XmlNode xmlGame = doc.SelectSingleNode(string.Format("//machine[@name='{0}']", key));
```

**Comment by mika76** [comment]
Thanks @nullpainter I updated it. I can't believe it's been 11 years since I worked on this last 🤣 I took it a little while ago to move to github but probably forgot half way. I've updated the project, but only have a windows VM running on MacOS at the moment, so if you have a chance please test it out and let me know if it works ok. Cheers 👍

**Comment by nullpainter** [comment]
Have verified that the game list now builds correctly.
